version: '3.3'

services:
  redis: 
    image: redis:alpine
    container_name: redis 
    command: ["--requirepass", "ladidadi"]
    ports: 
    - "6379:6379" 
    expose: 
    - "6379"
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: